### ISSUE TITLE
Provide a different iterator for each Connection instance

### ISSUE THREAD

**Issue by Renegade334** [PSchwisow/phergie-irc-plugin-react-altnick#1]
Currently, the plugin only has a single alt-nick iterator. If more than one connection requires an alt-nick, they will race to the remaining iterator values.

Instead, the plugin should create a new iterator for each connection instance that requests an alt-nick, stored in an internal `SplObjectStorage` object or similar.

**Comment by PSchwisow** [comment]
Fixed!
